# Qodana configuration for local runs
version: "1.0"

profile:
  name: qodana.starter

linter: jetbrains/qodana-js:latest

exclude:
  - name: All
    paths:
      - node_modules
      - backend/node_modules
      - frontend/node_modules
      - dist
      - build
      - .git
      - .vscode
      - coverage
      - "*.min.js"
      - "*.bundle.js"

bootstrap: |
  echo "Installing dependencies..."
  cd backend && npm install --legacy-peer-deps && cd ..
  cd frontend && npm install --legacy-peer-deps && cd ..
